# Generated by Django 2.2 on 2019-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='leftScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='rightScore',
            field=models.IntegerField(default=0),
        ),
    ]
